name: Terraform Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write       # required for OIDC
  actions: read

jobs:
  build_and_deploy_infra:
    name: Build and Deploy Infrastructure
    # Single approval happens here
    environment: production
    runs-on: ubuntu-latest
    outputs:
      acr_name: ${{ steps.tfout.outputs.acr_name }}
      acr_login_server: ${{ steps.tfout.outputs.acr_login_server }}
      resource_group_name: ${{ steps.tfout.outputs.resource_group_name }}
      web_app_name: ${{ steps.tfout.outputs.web_app_name }}
    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false tfplan
      
      - name: Get Terraform Outputs
        if: github.ref == 'refs/heads/main'
        id: tfout
        run: |
          echo "acr_name=$(terraform output -raw acr_name)" >> $GITHUB_OUTPUT
          echo "acr_login_server=$(terraform output -raw acr_login_server)" >> $GITHUB_OUTPUT
          echo "resource_group_name=$(terraform output -raw resource_group_name)" >> $GITHUB_OUTPUT
          echo "web_app_name=$(terraform output -raw web_app_name)" >> $GITHUB_OUTPUT

  deploy_app_code:
    name: Build and Deploy Application
    needs: build_and_deploy_infra
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # <-- no environment here; no second approval

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: az acr login --name ${{ needs.build_and_deploy_infra.outputs.acr_name }}

      - name: Build and Push Docker Image
        run: |
          ACR_SERVER=${{ needs.build_and_deploy_infra.outputs.acr_login_server }}
          IMAGE_NAME="secureapp"

          # Use context "terraform" so COPY can see terraform/www/*
          docker build -t $IMAGE_NAME -f terraform/app/Dockerfile terraform
          
          docker tag $IMAGE_NAME $ACR_SERVER/$IMAGE_NAME:${{ github.sha }}
          docker tag $IMAGE_NAME $ACR_SERVER/$IMAGE_NAME:latest
          
          docker push $ACR_SERVER/$IMAGE_NAME:${{ github.sha }}
          docker push $ACR_SERVER/$IMAGE_NAME:latest
      
      - name: Restart Web App to pull latest image
        run: |
          az webapp restart --name ${{ needs.build_and_deploy_infra.outputs.web_app_name }} --resource-group ${{ needs.build_and_deploy_infra.outputs.resource_group_name }}
