name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Upiši: destroy'
        required: true
        default: 'nope'

permissions:
  contents: read

jobs:
  destroy:
    if: github.event.inputs.confirmation == 'destroy'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (service principal JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: terraform init

      - name: Download state artifact from last deploy
        uses: dawidd6/action-download-artifact@v3
        with:
          name: tfstate-main
          path: .
          # Ako ima više runova, uzima zadnji sa glavne grane:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: List files (debug)
        run: ls -la

      - name: Terraform Destroy
        env:
          TF_INPUT: 0
        run: terraform destroy -auto-approve
