name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "destroy" to confirm teardown.'
        required: true
        default: 'do-not-destroy'

permissions:
  contents: read

jobs:
  destroy:
    if: ${{ github.event.inputs.confirmation == 'destroy' }}
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download state from last successful Deploy run
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: 'Terraform Deploy'
          workflow_conclusion: success
          name: tfstate-main
          branch: main
          path: terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        run: terraform init -input=false -upgrade

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
