name: Terraform Destroy

on:
  workflow_dispatch:
  push:
    branches: [ "rollback-destroy" ]

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Download Terraform state from last Deploy
        uses: actions/download-artifact@v4
        with:
          name: tfstate-main
          path: terraform

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
